### ISSUE TITLE
Result should return the first result as documented in the plugin source code

### ISSUE THREAD

**Issue by hugoatjoget** [jogetoss/column-search-hash-variable#3]
https://github.com/jogetoss/column-search-hash-variable/blob/13ded74c957b6002909f3cf23b9fd9d17e8905f9/src/main/java/org/joget/marketplace/FormColumnSearchHash.java#L88C33-L88C33

**Comment by miaoxng** [comment]
If there are more than one results for one hash, it will return the most recent input result into the database.

**Comment by miaoxng** [comment]
Resolved with release 8.0.3 to only get the first returned hash result. 
When resultset is looped, we get the first value and break the loop.
